# -*- coding: utf-8 -*-
"""1. Calculadora Inteligente.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qda_-JfZXaS18QqQzZXtZBXKnCCzB4UA

**Critérios obrigatórios:**

* Usar o comando 'input' para receber ao menos 2 números de entrada do usuário;
* Converter os valores recebidos pelo usuário para número inteiro (int) ou ponto flutuante (float);
* Implementar ao menos 4 operações matemáticas no código;
* Adicionar um laço de repetição ou uma condicional. Exemplo: permitir que o usuário escolha qual operação realizar ou criar um loop que permita ao usuário realizar várias operações consecutivas;
* Usar o comando 'print' para exibir o resultado da operação matemática.
"""

print('Seja bem vindo(a) à Calculadora Inteligente!')

# O programa rodará em loop enquanto o usuário digitar valores do tipo int e float

# Solicita que o usuário digite o primeiro número
while True:
  try:
    val1_float = float(input('Digite o primeiro número: '))

    # Verifica se o número é um inteiro
    if val1_float.is_integer():
      val1 = int(val1_float) # Se sim, converte para int
    else:
      val1 = val1_float # Se não, mantém como float

    break # Sai do loop se o usuário digitar um valor válido
  except ValueError: # Para o caso de o usuário digitar um valor que não seja um número
    print('Valor inválido. Por favor, digite um número.')

# Solicita que o usuário digite o segundo número
while True:
  try:
    val2_float = float(input('Digite o segundo número: '))

    if val2_float.is_integer():
      val2 = int(val2_float)
    else:
      val2 = val2_float

    break # Sai do loop se o usuário digitar um valor válido
  except ValueError: # Para o caso de o usuário digitar um valor que não seja um número
    print('Valor inválido. Por favor, digite um número.')

# Operações aritméticas possíveis com o valores indicados pelo usuário

soma = val1 + val2    # Soma os valores
print('O resultado da soma dos valores é: ', soma)

sub = val1 - val2     # Subtrai os valores
print('O resultado da subtração dos valores é: ', sub)

mult = val1 * val2    # Multiplica os valores
print('O resultado da multiplicação entre eles é: ', mult)

div1 = val1 / val2    # Divide o primeiro pelo segundo valor
print('O resultado do primeiro valor dividido pelo segundo é: ', div1)

div2 = val2 / val1    # Divide o segundo pelo primeiro valor
print('O resultado do segundo valor dividido pelo primeiro é: ', div2)

if val1 > val2:
  print('O primeiro é maior que o segundo')
elif val1 < val2:
  print('O primeiro é menor que o segundo')
else:
  print('Os valores são iguais')